### ISSUE TITLE
Add rultor configuration

### ISSUE THREAD

**Issue by GilraenBurland** [GilraenBurland/roster#7]
See: http://doc.rultor.com/reference.html

**Comment by GilraenBurland** [comment]
@rultor hello

**Comment by GilraenBurland** [comment]
@rultor status

**Comment by GilraenBurland** [comment]
@rultor config

**Comment by GilraenBurland** [comment]
@rultor config

**Comment by GilraenBurland** [comment]
@rultor release, tag is `0.1`

**Comment by GilraenBurland** [comment]
@rultor release, tag=`1.7`

**Comment by GilraenBurland** [comment]
@rultor release, tag=`0.1`

**Comment by GilraenBurland** [comment]
@rultor config

**Comment by GilraenBurland** [comment]
@rultor release, tag=`0.1`

**Comment by yegor256** [comment]
@rultor hello

**Comment by GilraenBurland** [comment]
@rultor merge please

**Comment by GilraenBurland** [comment]
@rultor release, tag=`0.1`

**Comment by GilraenBurland** [comment]
@rultor release, tag=`0.1`

**Comment by GilraenBurland** [comment]
@rultor release please, tag=`0.1`

**Comment by GilraenBurland** [comment]
@rultor release please, tag=`0.1`

**Comment by GilraenBurland** [comment]
@rultor release, tag=`0.1`

**Comment by GilraenBurland** [comment]
@rultor release, tag is `0.1.1`
